### ISSUE TITLE
Installation and database setup procedure problems

### ISSUE THREAD

**Issue by yansergi** [XOTlC/Blacket#95]
I'm installing Blacket on Raspberry Pi.

The step
> Start an instance of Blacket:
> ```
> node .
> ```

fails with:
```
pi@pi4:~/blacket/backend $ node .
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '/home/pi/blacket/backend'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.11.1
```

Instead, looks like it needs to be something like
```
cd src
SERVER_DATABASE_DIALECT=sqlite SERVER_DATABASE_USERNAME=pi node index.js
```

Apparently, `localhost:3000` step was supposed to set up the database connection. Perhaps by serving files in `src/public`. I see no way to start serving them, though. I see a few references to `express`, but no clear entry point.

Side note.

I also tried `SERVER_DATABASE_DIALECT=sqlite`, in order not to jump through all hoops of MySQL, but it failed this way:
```
pi@pi4:~/blacket/backend/src $ SERVER_DATABASE_DIALECT=sqlite SERVER_DATABASE_USERNAME=pi node index.js 
[INFO] Starting Blacket server instance...
[INFO] Authenticating to SQLite database...
[SUCCESS] Authenticated with SQLite database.
[INFO] Loading database models...
[SUCCESS] Loaded 23 database model(s).
[INFO] Syncing database models...
[SUCCESS] Synced database models.
/home/pi/blacket/backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1743
      throw new Error(`WHERE parameter "${key}" has invalid "undefined" value`);
            ^

Error: WHERE parameter "username" has invalid "undefined" value
    at SQLiteQueryGenerator.whereItemQuery (/home/pi/blacket/backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1743:13)
    at /home/pi/blacket/backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1734:25
    at Array.forEach (<anonymous>)
    at SQLiteQueryGenerator.whereItemsQuery (/home/pi/blacket/backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1732:35)
    at SQLiteQueryGenerator.getWhereConditions (/home/pi/blacket/backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2075:19)
    at SQLiteQueryGenerator.selectQuery (/home/pi/blacket/backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:988:28)
    at SQLiteQueryInterface.select (/home/pi/blacket/backend/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:59)
    at User.findAll (/home/pi/blacket/backend/node_modules/sequelize/lib/model.js:1140:47)
    at async User.findOne (/home/pi/blacket/backend/node_modules/sequelize/lib/model.js:1240:12)
    at async User.findOrCreate (/home/pi/blacket/backend/node_modules/sequelize/lib/model.js:1411:21)

Node.js v20.11.1
```

**Comment by notalicialol** [comment]
Not sure why Xotic hasn't touched this...

Are you trying to install the current Blacket files onto your Raspberry Pi?

**If yes:**
Firstly, that is the **Blacket Rewrite** which will be under development until stable. Second, I'm not sure you set it up properly?

**If no:** I'm not sure you set it up your database properly. Your model.js it looking for a username collection or something similar in your database...

Is that right?

**Comment by microcrit** [comment]
Please pull the latest source and use https://setup.blacket.org/ to create a config. Also follow what @notalicialol said
